### ISSUE TITLE
Scott Adams and AppImage

### ISSUE THREAD

**Issue by cspiegel** [angstsmurf/garglk#2]
I just updated Gargoyle's AppImage builders to the latest version (I'd pinned them at an older version to fix a broken build, ironically). I did a test and it seems to fix the build for the new interpreters you've added, if you want to give it a shot in your branch.

If that passes, any reason not to get these merged in?

**Comment by angstsmurf** [comment]
I'd love to get them merged in, but they seem to have a problem with Gargoyle's handling of timers, input and drawing routines which causes games to stop responding to input during certain animations.

If you have any idea of how that could be fixed, I'd be happy to help. Alternatively, we could try to simply disable or slow down the animations.

A good test case is [_Rebel Planet_](https://www.worldofspectrum.org//pub/sinclair/games/r/RebelPlanet.tzx.zip), which will soft lock at the very first screen.

**Comment by angstsmurf** [comment]
I'll close this. Something just broke the macOS qt builds (seems to be a Homebrew problem), but that is a matter for a separate issue report.

**Comment by cspiegel** [comment]
Yeah, I saw that break a couple days ago; something happened outside of Gargoyle, and is affecting other projects: https://github.com/actions/runner-images/issues/6817

There are workarounds listed there, but I'm hoping the runner gets fixed so I don't have to use a workaround.  I'm keeping an eye on this issue, and will modify the action if it doesn't get resolved soonish.
